stages:
  - build
  - security

build-docker:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker-compose up -d

enter-nix-dev-shell:
  stage: build
  image: nixpkgs/nix-flakes:latest
  services:
    - docker:dind
  script:
    - nix develop .

security-scan:
  stage: security
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy fs --scanners vuln --severity CRITICAL,HIGH,MEDIUM,LOW --include-dev-deps --format json -o trivy-report.json .
  artifacts:
    paths:
      - trivy-report.json
    expire_in: 2 weeks
