networks:
  network:  # Define the network
    ipam:
      driver: default
      config:
        - subnet: 14.0.0.0/24  # Define the subnet for the custom network

services:
  api-chi:
    build:
      dockerfile: ./docker/api-chi/Dockerfile
    environment:
      # Database
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_PUBLIC_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}

      # Auth
      AUTH_USERNAME: ${AUTH_USERNAME}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
      AUTH_BCRYPT_COST: ${AUTH_BCRYPT_COST}

      # Api
      API_PORT: ${API_PORT}

      # Web
      WEB_HOST: ${WEB_PUBLIC_HOST}
      WEB_PORT: ${WEB_PORT}
    ports:
      - '${API_PUBLIC_PORT}:${API_PORT}'
    networks:
      network:
        ipv4_address: ${API_PUBLIC_HOST}

  database-postgresql:
    build:
      dockerfile: ./docker/database-postgresql/Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '${POSTGRES_PUBLIC_PORT}:${POSTGRES_PORT}'
    networks:
      network:
        ipv4_address: ${POSTGRES_PUBLIC_HOST}

  web-next-ts:
    build:
      dockerfile: ./docker/web-next-ts/Dockerfile
    ports:
      - '${WEB_PUBLIC_PORT}:${WEB_PORT}'
    environment:
      API_HOST: '0.0.0.0'
      API_PORT: ${API_PORT}
      NUXT_HOST: '0.0.0.0'
      NUXT_PORT: ${WEB_PORT}
    networks:
      network:
        ipv4_address: ${WEB_PUBLIC_HOST}
