networks:
  network:  # Define the network
    ipam:
      driver: default
      config:
        - subnet: 14.0.0.0/24  # Define the subnet for the custom network

services:
  api-chi:
    build:
      dockerfile: ./docker/api-chi/Dockerfile
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_PUBLIC_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}

      API_PORT: ${API_PORT}
    ports:
      - '${API_PUBLIC_PORT}:${API_PORT}'
    networks:
      network:
        ipv4_address: 14.0.0.3

  database-postgresql:
    build:
      dockerfile: ./docker/database-postgresql/Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '${POSTGRES_PUBLIC_PORT}:${POSTGRES_PORT}'
    networks:
      network:
        ipv4_address: 14.0.0.5

  web-nuxt:
    build:
      dockerfile: ./docker/web-nuxt/Dockerfile
    ports:
      - '14004:3000'
    networks:
      network:
        ipv4_address: 14.0.0.4
