networks:
  network:  # Define the network
    ipam:
      driver: default
      config:
        - subnet: 14.0.0.0/24  # Define the subnet for the custom network

services:
  api-chi:
    build:
      dockerfile: ./docker/api-chi/Dockerfile
    ports:
      - '14003:3000'
    networks:
      network:
        ipv4_address: 14.0.0.3

  database-postgresql:
    build:
      dockerfile: ./docker/database-postgresql/Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '14005:5432'
    networks:
      network:
        ipv4_address: 14.0.0.5

  web-nuxt:
    build:
      dockerfile: ./docker/web-nuxt/Dockerfile
    ports:
      - '14004:3000'
    networks:
      network:
        ipv4_address: 14.0.0.4
