name: Github Actions
run-name: ${{ github.actor }} is running Github Actions 🚀
on:
  push:
    branches:
      - '*'

jobs:
  build-docker:
    name: Build docker
    runs-on: ubuntu-24.04

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup Docker, Docker compose and build start
      uses: hoverkraft-tech/compose-action@v2.0.1

  enter-nix-shell:
    name: Enter nix shell
    runs-on: ubuntu-24.04

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup nix
      uses: cachix/install-nix-action@v27

    - name: Enter nix flake devshell
      run: nix develop .
      if: always()

  test-route-blogtag-docker:
    name: Build and test route blogtag docker
    runs-on: ubuntu-24.04

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup Docker, Docker compose and build start
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        services: |
          database-postgresql
          api-chi

    - name: Test api-chi route blogtag
      run: sh scripts/test.bash api-route-blogtag


  test-service-blogtag-docker:
    name: Build and test service blogtag docker
    runs-on: ubuntu-24.04

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup Docker, Docker compose and build start
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        services: |
          database-postgresql
          api-chi

    - name: Test api-chi service blogtag
      run: sh scripts/test.bash api-service-blogtag

